run_navier_stokes_test_cases:
	@cd navier_stokes; sh run_all.sh
run_volume_of_fluid_test_cases:
	@cd volume_of_fluid; sh run.sh
run_immersed_boundary_method_test_cases:
	@cd immersed_boundary_method; sh run.sh
